In [2]:
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
# 10 NIFTY 50 stocks - different sectors
tickers = [
    # Banking
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "KOTAKBANK.NS",
    
    # IT
    "TCS.NS",
    "INFY.NS",
    "WIPRO.NS",
    
    # Energy
    "RELIANCE.NS",
    "ONGC.NS",
    
    # FMCG
    "HINDUNILVR.NS",
    
    # Auto
    "MARUTI.NS"
]

print(f"Total stocks: {len(tickers)}")
print("Sectors covered: Banking, IT, Energy, FMCG, Auto")

Total stocks: 10
Sectors covered: Banking, IT, Energy, FMCG, Auto

In [8]:
raw_data = yf.download(tickers, start = "2020-01-01", end = "2025-01-01")

close_prices  = raw_data["Close"]

print("Shape:", close_prices.shape)
print("\nColumns:", close_prices.columns.tolist())

close_prices.head()

[*********************100%***********************]  10 of 10 completed

Shape: (1238, 10)

Columns: ['HDFCBANK.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'INFY.NS', 'KOTAKBANK.NS', 'MARUTI.NS', 'ONGC.NS', 'RELIANCE.NS', 'TCS.NS', 'WIPRO.NS']

Ticker,HDFCBANK.NS,HINDUNILVR.NS,ICICIBANK.NS,INFY.NS,KOTAKBANK.NS,MARUTI.NS,ONGC.NS,RELIANCE.NS,TCS.NS,WIPRO.NS
Date,,,,,,,,,,
2020-01-01,605.529358,1749.931396,519.138000,633.151123,333.417084,6945.335449,85.371376,672.216125,1841.149780,113.709183
2020-01-02,609.389160,1751.286865,522.861572,631.303650,332.919128,6962.575195,85.773300,683.660217,1832.698120,113.984612
2020-01-03,600.698792,1741.708374,521.169006,641.013367,330.041168,6890.763672,86.041237,684.484009,1869.221680,115.270004
2020-01-06,587.698853,1730.864502,508.450531,634.869690,329.134949,6689.528809,84.567574,668.609314,1869.052368,115.751991
2020-01-07,597.004761,1735.608643,505.742432,625.460693,332.779724,6719.166016,84.232666,678.895691,1873.638794,117.152122

In [13]:
df_long =  close_prices.reset_index().melt(
    id_vars = "Date",
    var_name = "Tickers",
    value_name = "Close"
)

print("Shape: ", df_long.shape)
print("\nFirst 10 rows: ")
df_long.head(-10)

Shape:  (12380, 3)

First 10 rows:

            Date      Tickers       Close
0     2020-01-01  HDFCBANK.NS  605.529358
1     2020-01-02  HDFCBANK.NS  609.389160
2     2020-01-03  HDFCBANK.NS  600.698792
3     2020-01-06  HDFCBANK.NS  587.698853
4     2020-01-07  HDFCBANK.NS  597.004761
...          ...          ...         ...
12365 2024-12-10     WIPRO.NS  288.813141
12366 2024-12-11     WIPRO.NS  289.656769
12367 2024-12-12     WIPRO.NS  289.750519
12368 2024-12-13     WIPRO.NS  290.547363
12369 2024-12-16     WIPRO.NS  289.844299

[12370 rows x 3 columns]

In [14]:
df_long.to_csv("../data/ten_stocks_long.csv", index = False)
close_prices.to_csv("../data/ten_stocks_wide.csv")

print("Saved!")

Saved!

In [16]:
#Stock wise avg close price

avg_stock_price = df_long.groupby("Tickers")["Close"].mean().round(2)

print("Average Close Price (2020-2025): ")
for ticker, price in avg_stock_price.sort_values(ascending = False).items():
    print(f"{ticker} : Rs. {price}")

Average Close Price (2020-2025):
MARUTI.NS : Rs. 8402.45
TCS.NS : Rs. 2948.57
HINDUNILVR.NS : Rs. 2263.64
INFY.NS : Rs. 1299.01
RELIANCE.NS : Rs. 1095.1
ICICIBANK.NS : Rs. 775.96
HDFCBANK.NS : Rs. 703.89
KOTAKBANK.NS : Rs. 348.15
WIPRO.NS : Rs. 205.08
ONGC.NS : Rs. 131.97